tap "homebrew/bundle"
tap "homebrew/services"
tap "oven-sh/bun"

brew "bun"
brew "coreutils"
brew "direnv"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "go"
brew "mise"
brew "neovim"
brew "openssl@3"
brew "parallel"
brew "postgresql@17", restart_service: true
brew "ripgrep"
brew "rustup"
brew "tldr"
brew "tree"
brew "uv"
brew "yarn"
brew "zoxide"

cask "alfred"
cask "iterm2"
cask "visual-studio-code"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "notion"
